import { useEffect, useState } from "react";
import { FiArrowDownCircle, FiArrowUpCircle, FiBriefcase, FiClock, FiDollarSign, FiFileText, FiLock, FiPlus, FiSearch, FiTrendingUp } from "react-icons/fi";
import { useAuth } from "../../context/AuthContext";
import { useStore } from "../../context/StoreContext";
import { ROLES } from "../../config/roles";
import { formatPrice } from "../../utils/formatPrice";
import { saleGrossPaymentBreakdown, saleNetPaymentBreakdown, saleNetRevenue } from "../../utils/reporting";
import { formatWorkspaceDate, workspaceDateISO, workspaceBusinessDateISO, workspaceTime } from "../../utils/workspaceDate";
import { PageHeader, StatCard, StatusBadge, PremiumSelect, ColumnPicker } from "../../components/Ui";
import Modal from "../../components/Modal";
import { useFeedback } from "../../context/FeedbackContext";
import useUnsavedGuard from "../../utils/useUnsavedGuard";
import usePersistentColumns from "../../utils/usePersistentColumns";
import "./shifts.scss";

const CASH_DENOMINATIONS=[200000,100000,50000,20000,10000,5000,2000,1000];

function Shifts(){
  const {currentUser}=useAuth();
  const {confirm,notify}=useFeedback();
  const {activeShift,shiftHistory,dailySales,commitShiftOpen,commitShiftMovement,commitShiftClose,currentStore,currentStoreId,hasPermission,effectiveWorkspaceSettings:workspaceSettings}=useStore();
  const [openModal,setOpenModal]=useState(false);const [closeModal,setCloseModal]=useState(false);const [moveModal,setMoveModal]=useState(null);const [reportShift,setReportShift]=useState(null);
  const [openingCash,setOpeningCash]=useState("");const [actualCash,setActualCash]=useState("");const [moveAmount,setMoveAmount]=useState("");const [moveReason,setMoveReason]=useState("");const [differenceReason,setDifferenceReason]=useState("");
  const [useDenominations,setUseDenominations]=useState(false);const [denominationCounts,setDenominationCounts]=useState({});
  const [search,setSearch]=useState("");const [statusFilter,setStatusFilter]=useState("all");const [tick,setTick]=useState(Date.now());
  const shiftColumnDefs=[{id:"opening",label:"Boshlang‘ich"},{id:"sales",label:"Savdo"},{id:"expected",label:"Kutilgan"},{id:"actual",label:"Haqiqiy"},{id:"difference",label:"Farq"},{id:"duration",label:"Davomiylik"}];
  const {visible:shiftColumns,toggle:toggleShiftColumn,show:showShiftColumn}=usePersistentColumns("zenix_shift_history_columns",shiftColumnDefs);
  const openDraftDirty=openModal&&openingCash!=="";
  const moveDraftDirty=Boolean(moveModal)&&(moveAmount!==""||Boolean(moveReason.trim()));
  const closeDraftDirty=closeModal&&(actualCash!==""||Boolean(differenceReason.trim())||useDenominations||Object.values(denominationCounts).some((value)=>Number(value||0)>0));
  const guardOpenClose=useUnsavedGuard(openDraftDirty,"Smena ochish uchun kiritilgan boshlang‘ich naqd saqlanmagan.");
  const guardMoveClose=useUnsavedGuard(moveDraftDirty,"Kassa harakati uchun kiritilgan summa yoki izoh saqlanmagan.");
  const guardReconClose=useUnsavedGuard(closeDraftDirty,"Smena yopish uchun kiritilgan kassa sanog‘i saqlanmagan.");
  const canRecon=hasPermission("shiftRecon",currentUser?.appRole);
  const isCashier=currentUser?.appRole===ROLES.CASHIER;
  const currentIdentityIds=[currentUser?.employeeId,currentUser?.id].filter(Boolean).map(String);
  const ownsShift=(shift)=>{
    const identity=shift?.cashierId||shift?.cashierAccountId;
    return identity?currentIdentityIds.includes(String(identity)):shift?.cashierName===currentUser?.name;
  };
  const shiftSales=activeShift ? dailySales.filter((sale)=>sale.shiftId===activeShift.id) : [];
  const salesTotal=shiftSales.reduce((sum,sale)=>sum+saleNetRevenue(sale),0);
  const paymentMix=shiftSales.reduce((totals,sale)=>{const mix=saleNetPaymentBreakdown(sale);return {cash:totals.cash+mix.cash,card:totals.card+mix.card,transfer:totals.transfer+mix.transfer}}, {cash:0,card:0,transfer:0});
  // Cash refunds/expenses are already recorded as signed shift movements by the
  // backend. Use gross cash sales for reconciliation so those movements are not
  // subtracted a second time in the expected-cash calculation.
  const cashSales=shiftSales.reduce((sum,sale)=>sum+saleGrossPaymentBreakdown(sale).cash,0);
  const cashIn=(activeShift?.cashMovements||[]).filter(x=>x.type==="in").reduce((s,x)=>s+x.amount,0);const cashOut=(activeShift?.cashMovements||[]).filter(x=>x.type==="out").reduce((s,x)=>s+x.amount,0);
  const expected=Number(activeShift?.openingCash||0)+cashSales+cashIn-cashOut;const denominationTotal=CASH_DENOMINATIONS.reduce((sum,value)=>sum+value*Math.max(0,Number(denominationCounts[value]||0)),0);const countedCash=useDenominations?denominationTotal:Number(actualCash||0);const diff=countedCash-expected;
  useEffect(()=>{if(!activeShift)return;setTick(Date.now());const timer=setInterval(()=>setTick(Date.now()),30000);return()=>clearInterval(timer)},[activeShift]);
  const duration=activeShift?Math.max(0,tick-new Date(activeShift.openedAtISO).getTime()):0;const durationText=activeShift?`${Math.floor(duration/3600000)} soat ${Math.floor((duration%3600000)/60000)} daqiqa`:"—";
  const maxShiftHours=Math.max(1,Number(workspaceSettings.businessDay?.maxShiftHours||12));
  const longShift=Boolean(activeShift&&duration>=maxShiftHours*3600000);
  const businessClose=workspaceSettings.businessDay?.closeTime||"23:59";
  const warnBeforeClose=Math.max(0,Number(workspaceSettings.businessDay?.warnBeforeCloseMinutes||0));
  const localClock=workspaceTime(new Date(),workspaceSettings.organization).slice(0,5);
  const toMinutes=(value)=>{const [hours,minutes]=String(value||"00:00").split(":").map(Number);return Math.max(0,Math.min(1439,(hours||0)*60+(minutes||0)))};
  const minutesUntilClose=(toMinutes(businessClose)-toMinutes(localClock)+1440)%1440;
  const closeWarning=Boolean(activeShift&&warnBeforeClose>0&&minutesUntilClose<=warnBeforeClose);
  const closeOpenShiftModal=()=>guardOpenClose(()=>{setOpenModal(false);setOpeningCash("")});
  const closeMoveShiftModal=()=>guardMoveClose(()=>{setMoveModal(null);setMoveAmount("");setMoveReason("")});
  const closeReconciliationModal=()=>guardReconClose(()=>{setCloseModal(false);setActualCash("");setDifferenceReason("");setUseDenominations(false);setDenominationCounts({})});
  const openShift=async()=>{
    const amount=Math.max(0,Number(openingCash||0));const now=new Date();
    const shift={id:`SH-${crypto.randomUUID().slice(0,8).toUpperCase()}`,cashierId:currentUser?.employeeId||currentUser?.id,cashierAccountId:currentUser?.id,cashierName:currentUser?.name,storeName:currentStore?.name,storeId:currentStoreId,openingCash:amount,openedAt:workspaceTime(now,workspaceSettings.organization),openedAtISO:now.toISOString(),date:formatWorkspaceDate(now,workspaceSettings.organization),dateISO:workspaceDateISO(now,workspaceSettings.organization.timezone),businessDateISO:workspaceBusinessDateISO(now,workspaceSettings.organization,workspaceSettings.businessDay),status:"open",cashMovements:[]};
    const result=await commitShiftOpen({shift,activity:{type:"shift",title:"Smena ochildi",description:`Boshlang‘ich kassa ${formatPrice(amount)}`}});
    if(!result?.success){notify({tone:"danger",title:"Smena ochilmadi",message:result?.message||"Qayta urinib ko‘ring."});return}
    setOpenModal(false);setOpeningCash("");notify({tone:"success",title:"Smena ochildi",message:`Boshlang‘ich kassa · ${formatPrice(amount)}`});
  };
  const addMovement=async()=>{
    if(!canRecon&&!ownsShift(activeShift))return;const amount=Number(moveAmount||0);if(amount<=0||!moveReason.trim())return;
    const movementType=moveModal;const movement={id:crypto.randomUUID(),type:movementType,amount,reason:moveReason,time:workspaceTime(new Date(),workspaceSettings.organization)};
    const result=await commitShiftMovement({movement,storeId:currentStoreId,activity:{type:"shift",title:movementType==="in"?"Kassa kirimi":"Kassa chiqimi",description:`${moveReason} · ${formatPrice(amount)}`}});
    if(!result?.success){notify({tone:"danger",title:"Kassa harakati saqlanmadi",message:result?.message||"Qayta urinib ko‘ring."});return}
    setMoveModal(null);setMoveAmount("");setMoveReason("");notify({tone:"success",title:movementType==="in"?"Kassa kirimi saqlandi":"Kassa chiqimi saqlandi",message:formatPrice(amount)});
  };
  const closeShift=async()=>{
    if(!activeShift)return;if(!canRecon&&!ownsShift(activeShift))return;const actual=countedCash;const difference=actual-expected;if(Math.abs(difference)>0&&!differenceReason.trim())return;
    const now=new Date();const closed={...activeShift,closedAt:workspaceTime(now,workspaceSettings.organization),closedAtISO:now.toISOString(),closingCash:actual,expectedCash:expected,difference,totalSales:salesTotal,cashSales,cardSales:paymentMix.card,transferSales:paymentMix.transfer,cashIn,cashOut,duration:durationText,status:"closed",differenceReason,denominationCounts:useDenominations?denominationCounts:null};
    const result=await commitShiftClose({closedShift:closed,storeId:currentStoreId,activity:{type:"shift",title:"Smena yopildi",description:`Kassa farqi ${formatPrice(difference)}`}});
    if(!result?.success){notify({tone:"danger",title:"Smena yopilmadi",message:result?.message||"Qayta urinib ko‘ring."});return}
    setCloseModal(false);setActualCash("");setDifferenceReason("");setUseDenominations(false);setDenominationCounts({});notify({tone:"success",title:"Smena yopildi",message:`Farq · ${difference>0?"+":""}${formatPrice(difference)}`});
  };
  const requestCloseShift=async()=>{if(!activeShift)return;const accepted=await confirm({title:"Smenani yopasizmi?",message:`Kutilayotgan naqd ${formatPrice(expected)}, haqiqiy naqd ${formatPrice(countedCash)}. Farq ${diff>0?"+":""}${formatPrice(diff)}. Yopilgandan keyin smena moliyaviy tarixga yoziladi.`,confirmLabel:"Smenani yopish",cancelLabel:"Ortga",tone:"danger"});if(accepted)closeShift()};
  const filtered=shiftHistory.filter(s=>{const matchesStore=s.storeId?String(s.storeId)===String(currentStoreId):!s.storeName||s.storeName===currentStore?.name;return matchesStore&&(!isCashier||ownsShift(s))&&(statusFilter==="all"||s.status===statusFilter)&&`${s.cashierName} ${s.storeName||""} ${s.date}`.toLowerCase().includes(search.toLowerCase())});
  const latestStoreShift=shiftHistory.find((shift)=>shift.storeId?String(shift.storeId)===String(currentStoreId):!shift.storeName||shift.storeName===currentStore?.name);
  return <div className="pro-page shifts-pro"><PageHeader title="Kassa / Smena" subtitle="Kassani ochish, naqd pul harakatlari va smena yakunini nazorat qiling." actions={activeShift?<StatusBadge tone="success">Smena ochiq</StatusBadge>:<button className="pro-btn primary" onClick={()=>setOpenModal(true)}><FiPlus/> Smena ochish</button>}/>
    <div className="pro-stat-grid"><StatCard icon={FiTrendingUp} label="Sof savdo" value={formatPrice(salesTotal)} hint={`${shiftSales.length} ta tranzaksiya`} tone="green"/><StatCard icon={FiDollarSign} label="Kutilayotgan naqd" value={formatPrice(activeShift?expected:0)} hint="Qaytarish va chiqimlardan keyin" tone="blue"/><StatCard icon={FiClock} label="Smena davomiyligi" value={durationText} hint={activeShift?activeShift.openedAt:"Smena yopiq"} tone="purple"/><StatCard icon={FiFileText} label="Kassa farqi" value={activeShift?"Yopishda aniqlanadi":formatPrice(latestStoreShift?.difference||0)} hint="Smena yakuni" tone="orange"/></div>
    {!activeShift?<section className="shift-closed-card pro-card"><div className="shift-lock"><FiLock/></div><div><h2>Smena hozir yopiq</h2><p>Savdo qilish uchun kassir avval smenani ochishi kerak. Boshlang‘ich naqd summani kiriting va kassani ishga tayyorlang.</p></div><button className="pro-btn primary" onClick={()=>setOpenModal(true)}>Smenani ochish</button></section>:<section className="pro-card shift-live"><div className="shift-live-head"><div className="shift-live-identity"><div className="live-dot"/><span><small>Joriy smena</small><strong>{activeShift.cashierName} · {activeShift.storeName||currentStore?.name} · {activeShift.openedAt} da ochilgan</strong></span></div><div className="shift-actions"><button className="pro-btn secondary" onClick={()=>setMoveModal("in")}><FiArrowDownCircle/> Kassa kirimi</button><button className="pro-btn secondary" onClick={()=>setMoveModal("out")}><FiArrowUpCircle/> Kassa chiqimi</button><button className="pro-btn danger" onClick={()=>setCloseModal(true)}>Smenani yopish</button></div></div>{(longShift||closeWarning)&&<div className="pro-alert warning shift-business-warning"><FiClock/><span><strong>{longShift?"Smena juda uzoq davom etmoqda":"Biznes kuni yopilish vaqti keldi"}</strong><small>{longShift?`Belgilangan limit: ${maxShiftHours} soat. Smenani tekshirib, yakunlash tavsiya etiladi.`:`Yopilishgacha ${minutesUntilClose} daqiqa qoldi · ${businessClose}. Ochiq smenani yakunlashni unutmang.`}</small></span></div>}<div className="shift-metrics"><div><span>Boshlang‘ich naqd</span><strong>{formatPrice(activeShift.openingCash)}</strong></div><div><span>Naqd savdo</span><strong>{formatPrice(cashSales)}</strong></div><div><span>Karta / O‘tkazma</span><strong>{formatPrice(paymentMix.card+paymentMix.transfer)}</strong></div><div><span>Kassa kirimi</span><strong className="positive">+{formatPrice(cashIn)}</strong></div><div><span>Kassa chiqimi</span><strong className="negative">-{formatPrice(cashOut)}</strong></div><div className="expected"><span>Kutilayotgan naqd</span><strong>{formatPrice(expected)}</strong></div></div>{(activeShift.cashMovements||[]).length>0&&<div className="movement-list"><h3>So‘nggi kassa harakatlari</h3>{activeShift.cashMovements.slice(-5).reverse().map(m=><div key={m.id}><span className={m.type}>{m.type==="in"?<FiArrowDownCircle/>:<FiArrowUpCircle/>}<b>{m.reason}</b><small>{m.time}</small></span><strong>{m.type==="in"?"+":"-"}{formatPrice(m.amount)}</strong></div>)}</div>}</section>}
    <section className="pro-card shift-history-card"><div className="pro-card-head"><div><h2>Smena tarixi</h2><p>{isCashier?"Faqat o‘zingizning smenalaringiz.":"Kassirlar va filiallar bo‘yicha smena yakuni tarixi."}</p></div></div><div className="pro-toolbar"><div className="pro-search"><FiSearch/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Kassir, filial yoki sana..."/></div><PremiumSelect className="pro-select" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="all">Barcha holatlar</option><option value="closed">Yopilgan</option></PremiumSelect><ColumnPicker columns={shiftColumnDefs} visible={shiftColumns} onToggle={toggleShiftColumn}/></div><div className="pro-table-wrap mobile-card-wrap"><table className="pro-table mobile-card-table"><thead><tr><th>Sana / Kassir</th>{showShiftColumn("opening")&&<th>Boshlang‘ich</th>}{showShiftColumn("sales")&&<th>Savdo</th>}{showShiftColumn("expected")&&<th>Kutilgan</th>}{showShiftColumn("actual")&&<th>Haqiqiy</th>}{showShiftColumn("difference")&&<th>Farq</th>}{showShiftColumn("duration")&&<th>Davomiylik</th>}<th/></tr></thead><tbody>{filtered.length?filtered.map(s=><tr key={s.id}><td data-label="Sana / Kassir"><strong>{s.date}</strong><small>{s.cashierName} · {s.storeName||"Asosiy filial"}</small></td>{showShiftColumn("opening")&&<td data-label="Boshlang‘ich">{formatPrice(s.openingCash)}</td>}{showShiftColumn("sales")&&<td data-label="Savdo">{formatPrice(s.totalSales)}</td>}{showShiftColumn("expected")&&<td data-label="Kutilgan">{formatPrice(s.expectedCash??s.closingCash)}</td>}{showShiftColumn("actual")&&<td data-label="Haqiqiy">{formatPrice(s.closingCash)}</td>}{showShiftColumn("difference")&&<td data-label="Farq"><StatusBadge tone={Number(s.difference||0)===0?"success":Math.abs(Number(s.difference||0))<50000?"warning":"danger"}>{formatPrice(s.difference||0)}</StatusBadge></td>}{showShiftColumn("duration")&&<td data-label="Davomiylik">{s.duration||"—"}</td>}<td data-label="Amal"><button className="pro-btn secondary" onClick={()=>setReportShift(s)}>Hisobot</button></td></tr>):<tr><td colSpan={shiftColumns.length+2}><div className="pro-empty"><FiBriefcase/><strong>Smena tarixi yo‘q</strong><span>Yopilgan smenalar shu yerda ko‘rinadi.</span></div></td></tr>}</tbody></table></div></section>
    <Modal open={openModal} onClose={closeOpenShiftModal} title="Smena ochish" subtitle="Kassadagi boshlang‘ich naqd summani kiriting." size="sm" footer={<><button className="pro-btn secondary" onClick={closeOpenShiftModal}>Bekor qilish</button><button className="pro-btn primary" onClick={openShift}>Smenani ochish</button></>}><label className="pro-field"><span>Boshlang‘ich naqd</span><input data-modal-autofocus type="number" min="0" value={openingCash} onChange={e=>setOpeningCash(e.target.value)} placeholder="0"/></label></Modal>
    <Modal open={!!moveModal} onClose={closeMoveShiftModal} title={moveModal==="in"?"Kassa kirimi":"Kassa chiqimi"} subtitle="Har bir kassa harakati sabab bilan qayd qilinadi." size="sm" footer={<><button className="pro-btn secondary" onClick={closeMoveShiftModal}>Bekor qilish</button><button className="pro-btn primary" disabled={!moveAmount||!moveReason.trim()} onClick={addMovement}>Saqlash</button></>}><div className="pro-form-grid"><label className="pro-field full"><span>Summa</span><input data-modal-autofocus type="number" min="0" value={moveAmount} onChange={e=>setMoveAmount(e.target.value)}/></label><label className="pro-field full"><span>Sabab / izoh</span><textarea value={moveReason} onChange={e=>setMoveReason(e.target.value)} placeholder="Masalan: mayda pul qo‘shildi"/></label></div></Modal>
    <Modal open={closeModal} onClose={closeReconciliationModal} title="Smenani yopish" subtitle="Kassadagi haqiqiy naqd summani kiriting. Tizim kutilayotgan summa bilan solishtiradi." size="lg" footer={<><button className="pro-btn secondary" onClick={closeReconciliationModal}>Ortga</button><button className="pro-btn danger" disabled={(!useDenominations&&actualCash==="")||(diff!==0&&!differenceReason.trim())} onClick={requestCloseShift}>Smenani yopish</button></>}><div className="reconciliation"><div><span>Kutilayotgan naqd</span><strong>{formatPrice(expected)}</strong></div><button type="button" className={`denomination-toggle ${useDenominations?"active":""}`} onClick={()=>setUseDenominations(value=>!value)}><FiDollarSign/><span><strong>Kupuralar bo‘yicha sanash</strong><small>{useDenominations?`Hisoblangan: ${formatPrice(denominationTotal)}`:"Ixtiyoriy — kassir xatosini kamaytiradi"}</small></span><b>{useDenominations?"Yopish":"Ochish"}</b></button>{useDenominations&&<div className="denomination-grid">{CASH_DENOMINATIONS.map(value=><label key={value}><span>{formatPrice(value)}</span><input type="number" min="0" value={denominationCounts[value]||""} onChange={e=>setDenominationCounts(counts=>({...counts,[value]:Math.max(0,Number(e.target.value||0))}))} placeholder="0"/><small>{formatPrice(value*Math.max(0,Number(denominationCounts[value]||0)))}</small></label>)}</div>}<label className="pro-field"><span>Haqiqiy naqd</span><input data-modal-autofocus={!useDenominations} type="number" min="0" readOnly={useDenominations} value={useDenominations?denominationTotal:actualCash} onChange={e=>setActualCash(e.target.value)}/></label><div className={`recon-diff ${diff===0?"ok":diff>0?"plus":"minus"}`}><span>Farq</span><strong>{diff>0?"+":""}{formatPrice(diff)}</strong></div>{diff!==0&&<label className="pro-field"><span>Farq sababi *</span><textarea value={differenceReason} onChange={e=>setDifferenceReason(e.target.value)} placeholder="Farq sababini yozing"/></label>}</div></Modal>
    <Modal open={!!reportShift} onClose={()=>setReportShift(null)} title="Smena hisoboti" subtitle={reportShift?`${reportShift.id} · ${reportShift.cashierName}`:""}><div className="shift-report-grid">{reportShift&&[["Boshlang‘ich",reportShift.openingCash],["Savdo",reportShift.totalSales],["Kassa kirimi",reportShift.cashIn||0],["Kassa chiqimi",reportShift.cashOut||0],["Kutilgan",reportShift.expectedCash??reportShift.closingCash],["Haqiqiy",reportShift.closingCash],["Farq",reportShift.difference||0]].map(([l,v])=><div key={l}><span>{l}</span><strong>{formatPrice(v)}</strong></div>)}</div>{reportShift?.differenceReason&&<div className="pro-alert warning" style={{marginTop:12}}>Farq sababi: {reportShift.differenceReason}</div>}</Modal>
  </div>;
}
export default Shifts;
