import {chromium} from '@playwright/test';import {createServer} from 'vite';import {randomUUID} from 'node:crypto';import fs from 'node:fs/promises';import path from 'node:path';
import {posDraftKey} from '../src/utils/posDraft.js';
import {assertSafeTestDatabaseUrl} from '../../backend/scripts/assertTestDatabase.js';
assertSafeTestDatabaseUrl(process.env.TEST_DATABASE_URL,{nodeEnv:process.env.NODE_ENV});
if(process.env.DATABASE_URL!==process.env.TEST_DATABASE_URL)throw new Error('Test database required');
process.env.FRONTEND_ORIGIN='http://localhost:5173';process.env.VITE_API_URL='http://localhost:5179';
const [{app},{pool},{default:bcrypt}]=await Promise.all([import('../../backend/src/app.js'),import('../../backend/src/db/pool.js'),import('../../backend/node_modules/bcryptjs/index.js')]);
const out=path.resolve('../artifacts/prompt3');await fs.mkdir(out,{recursive:true});
let browser,vite,server;const evidence=[];
try{
 const suffix=randomUUID(),username='e2e-'+suffix,password=randomUUID()+'-Aa1!';
 const org=(await pool.query("INSERT INTO organizations(name,license_status,expiry_date,store_limit) VALUES('Prompt3 E2E','ACTIVE',CURRENT_DATE+30,2) RETURNING id")).rows[0].id;
 const store=(await pool.query("INSERT INTO stores(organization_id,name) VALUES($1,'Test filial') RETURNING id",[org])).rows[0].id;
 const user=(await pool.query("INSERT INTO users(organization_id,store_id,name,username,password_hash,app_role) VALUES($1,$2,'Test owner',$3,$4,'OWNER') RETURNING id",[org,store,username,await bcrypt.hash(password,10)])).rows[0].id;
 const product=(await pool.query("INSERT INTO products(organization_id,name,sku,unit,sell_price,cost_price) VALUES($1,'Ўзбекистон Ғалла — Grechka','E2E-KG','kg',12000,8000) RETURNING id",[org])).rows[0].id;
 await pool.query('INSERT INTO inventory_balances(organization_id,store_id,product_id,quantity,avg_cost) VALUES($1,$2,$3,30,8000)',[org,store,product]);
 await pool.query("INSERT INTO inventory_batches(organization_id,store_id,product_id,batch_no,received_quantity,remaining_quantity,unit_cost) VALUES($1,$2,$3,'Original lot',30,30,8000)",[org,store,product]);
 const customer=(await pool.query("INSERT INTO customers(organization_id,name,phone,credit_limit) VALUES($1,'Uzun ismli mijoz — Ўзбекистон мижози','998901234567',999999999) RETURNING id",[org])).rows[0].id;
 await pool.query("INSERT INTO customer_ledger(organization_id,customer_id,store_id,entry_type,amount,reference) VALUES($1,$2,$3,'CREDIT_SALE',123456789,'Test debt')",[org,customer,store]);
 await pool.query("INSERT INTO shifts(organization_id,store_id,cashier_id,status,opening_cash,expected_cash,register_key) VALUES($1,$2,$3,'open',1000000,1000000,'E2E')",[org,store,user]);
 server=app.listen(5179,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));
 vite=await createServer({server:{host:'127.0.0.1',port:5173,strictPort:true}});await vite.listen();
 browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});
 const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true}),page=await context.newPage();const errors=[];page.on('pageerror',error=>errors.push(error.message));
 await page.goto('http://localhost:5173/login');await page.locator('input[autocomplete="username"]').fill(username);await page.locator('input[type="password"]').fill(password);await page.locator('button[type="submit"]').click();await page.waitForURL('http://localhost:5173/');evidence.push('real owner login');
 await page.goto('http://localhost:5173/inventory');await page.getByRole('button',{name:'Inventarizatsiya',exact:true}).last().click();await page.locator('.revision-input').fill('15');await page.getByRole('button',{name:'Tasdiqlash',exact:true}).click();await page.waitForTimeout(800);
 const balance=(await pool.query('SELECT quantity FROM inventory_balances WHERE product_id=$1',[product])).rows[0];if(Number(balance.quantity)!==15)throw new Error('Batch count UI did not commit');evidence.push('batch inventory 30 → 15 browser → API → PostgreSQL');
 await page.getByRole('button',{name:'Tezkor kirim',exact:true}).click();const quick=page.getByRole('dialog',{name:'Tezkor kirim',exact:true});await quick.getByPlaceholder('Yangi mahsulot nomi').fill('E2E Olma');await quick.getByRole('button',{name:/lchov birligi$/}).click();await page.getByRole('option',{name:'kg',exact:true}).click();const numbers=quick.locator('.quick-receive-row input[type="number"]');await numbers.nth(0).fill('15.5');await numbers.nth(1).fill('8000');await numbers.nth(2).fill('12000');const received=page.waitForResponse(r=>r.url().includes('/api/inventory/receive')&&r.request().method()==='POST');await quick.getByRole('button',{name:'Barchasini qabul qilish'}).click();if(!(await received).ok())throw new Error('Quick receipt failed');await quick.waitFor({state:'hidden'});const apple=(await pool.query("SELECT p.unit,b.quantity FROM products p JOIN inventory_balances b ON b.product_id=p.id WHERE p.organization_id=$1 AND p.name='E2E Olma'",[org])).rows[0];if(apple?.unit!=='kg'||Number(apple.quantity)!==15.5)throw new Error('Quick receipt unit/quantity mismatch');evidence.push('quick receipt UI: 15.5 kg new product, server stock verified');
 const products=[];for(let i=0;i<100;i++){const id=(await pool.query("INSERT INTO products(organization_id,name,sku,unit,sell_price,cost_price) VALUES($1,$2,$3,'kg',100,25) RETURNING id",[org,'Product '+i,'E2E-'+i])).rows[0].id;await pool.query('INSERT INTO inventory_balances(organization_id,store_id,product_id,quantity,avg_cost) VALUES($1,$2,$3,10,25)',[org,store,id]);products.push({id,cartQty:1,name:'Product '+i,sellPrice:100,discountPercent:0});}
 await page.goto('http://localhost:5173/products');await page.getByRole('button',{name:'PDF eksport'}).waitFor();const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'PDF eksport'}).click();const download=await downloadPromise;await download.saveAs(path.join(out,'catalog.pdf'));evidence.push('real catalog PDF download');
 await page.goto('http://localhost:5173/customers');await page.locator('.customer-card').first().click();await page.locator('.customer-profile-head').waitFor();
 for(const width of [320,375,430,768,1440])for(const theme of ['light','dark']){
  await page.keyboard.press('Escape');await page.setViewportSize({width:1440,height:1000});if(await page.evaluate(()=>document.body.classList.contains('dark-mode'))!==(theme==='dark'))await page.getByRole('button',{name:'Mavzu',exact:true}).click();await page.locator('.customer-card').first().click();await page.locator('.customer-profile-head').waitFor();
  await page.setViewportSize({width,height:900});await page.screenshot({path:path.join(out,`customer-${width}-${theme}.png`),fullPage:true});
  const inputWidth=await page.locator('.customer-payment input').evaluate(el=>el.getBoundingClientRect().width);if(inputWidth<100)throw new Error(`Credit payment input collapsed ${width}: ${inputWidth}`);
  await page.locator('.pro-modal-body').evaluate(el=>el.scrollTop=el.scrollHeight);await page.screenshot({path:path.join(out,`customer-payment-${width}-${theme}.png`),fullPage:true});
  const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);if(overflow)throw new Error(`Customer viewport overflow ${width}`);
 }evidence.push('customer profile 320/375/430/768/1440 screenshots both themes; no document overflow');
 await page.keyboard.press('Escape');await page.setViewportSize({width:1440,height:1000});await page.reload();await page.waitForTimeout(700);if(!await page.evaluate(()=>document.body.classList.contains('dark-mode')))throw new Error('Manual dark reverted on refresh');evidence.push('manual dark persists across refresh and bootstrap');
 const draftKey=posDraftKey(org,user,store);
 for(const count of [1,10,30,100]){
  await page.goto('http://localhost:5173/customers');await page.evaluate(({key,cart})=>localStorage.setItem(key,JSON.stringify({v:1,cart,payment:'card',savedAt:Date.now()})),{key:draftKey,cart:products.slice(0,count)});await page.goto('http://localhost:5173/sales');await page.locator('.cart-item').nth(count-1).waitFor();
  for(const width of [320,375,430,1440]){
   await page.setViewportSize({width,height:900});if(width<768){const mobile=page.locator('.pos-mobile-pane-tabs [role="tab"]').filter({hasText:'Savat'});if(await mobile.count())await mobile.click();}
   const scroll=await page.locator('.cart-list').evaluate(el=>{el.scrollTop=el.scrollHeight;const bottom=el.scrollTop;el.scrollTop=0;return {bottom,top:el.scrollTop,needed:el.scrollHeight>el.clientHeight}});if(scroll.top!==0||(scroll.needed&&scroll.bottom<=0))throw new Error('Cart scroll stuck');
   await page.screenshot({path:path.join(out,`cart-${count}-${width}.png`),fullPage:true});
  }
 }evidence.push('actual independent cart scroll 1/10/30/100 lines at 320/375/430/1440');
 await page.setViewportSize({width:1440,height:1000});await page.getByRole('button',{name:'Savatni ushlab turish',exact:true}).first().click();await page.locator('.hold-row').getByRole('button',{name:'Savatni ushlab turish',exact:true}).click();await page.waitForTimeout(500);await page.reload();await page.getByRole('button',{name:'Savatni ushlab turish',exact:true}).first().click();await page.getByRole('button',{name:/Saqlangan savatlar/}).click();await page.getByRole('button',{name:'Davom ettirish',exact:true}).click();await page.locator('.cart-item').nth(99).waitFor();await page.locator('.payment-grid button').filter({hasText:'Karta'}).click();const posted=page.waitForResponse(response=>response.url().endsWith("/api/sales")&&response.request().method()==="POST",{timeout:15000});await page.locator('.checkout-primary').click();const confirmation=page.getByRole('dialog',{name:'Savdoni tasdiqlash'});await confirmation.waitFor({state:"visible",timeout:1500}).catch(()=>{});if(await confirmation.isVisible())await confirmation.getByRole('button',{name:/Tasdiqlash/}).click();const response=await posted;if(!response.ok())throw new Error(JSON.stringify((await response.json()).error));const sales=Number((await pool.query('SELECT count(*) FROM sales WHERE organization_id=$1',[org])).rows[0].count);if(sales!==1)throw new Error('Hold checkout did not create exactly one sale');evidence.push('hold → refresh → resume → checkout creates one sale');
 await page.waitForTimeout(1000);await page.keyboard.press('Escape');await page.locator('.pro-modal-backdrop').waitFor({state:'hidden'});await page.getByRole('button',{name:'Bugungi savdolar',exact:true}).click();await page.locator('.today-sales-list article').waitFor();await page.screenshot({path:path.join(out,'today-sales.png'),fullPage:true});evidence.push('today sales real item details API/modal');await page.keyboard.press('Escape');
 await page.goto('http://localhost:5173/activity-log');await page.waitForTimeout(600);await page.screenshot({path:path.join(out,'audit-desktop.png'),fullPage:true});
 if(errors.length)throw new Error(errors.join('\n'));
 await fs.writeFile(path.join(out,'evidence.json'),JSON.stringify({evidence,errors},null,2));console.log(JSON.stringify(evidence));
}catch(error){for(const context of browser?.contexts()||[])for(const page of context.pages())await page.screenshot({path:path.join(out,'failure-'+context.pages().indexOf(page)+'.png'),fullPage:true});throw error;}finally{await browser?.close();await vite?.close();if(server)await new Promise(resolve=>server.close(resolve));await pool.end()}
